### ISSUE TITLE
Doesn't appear to work for BTWifi-with-FON logins

### ISSUE THREAD

**Issue by karlic** [g0wfv/BTLogin#1]
It seems there are two types of BT hotspot: BT Wifi and BTWifi-with-FON. (I think BT Wifi has superseded BTWifi-with-FON.)

My username and password never allow me to use BT Wifi hotspots, but always allow me to use BTWifi-with-FON.

The method of access (URLs, etc.) are (slightly) different between the two and your script, as it stands, doesn't appear to work for me. I have, however, got it to work with some modifications. I thought you might like to add them to make your script more universal.

**Comment by g0wfv** [comment]
That's odd; I'm logged on and using a "with FON" hotspot right now ...?!

In fact, I can log on to both the "with FON" hotspots my OpenWRT router can hear.

By all means, though, submit a PR and I'll take a look.

**Comment by karlic** [comment]
BTW, I'm using your script because I lost my carefully crafted one after re-flashing. I had issues where sometimes networking would get screwed up, so the script used to try and log in, or restart networking, or reboot.

Does travelmate handle that eventuality, do you know?

**Comment by g0wfv** [comment]
I haven't the foggiest I'm afraid. Aside from the occasional forced logoff by BT, travelmate (along with this script) logs back in with maybe a couple of minutes downtime? It certainly recovers quite well. Uptime tends to be weeks, if not months before a reboot is required.

**Comment by karlic** [comment]
OK. Thanks. We'll see how it goes. :-)

I think the pull request is done---my brain's not working at the moment.
